name: Test and Check

# Triggered when code is pushed to any branch in a repository
on: [ push ]


jobs:
  Gradle_Test:
    runs-on: ubuntu-latest
    steps:
      # The checkout step downloads a copy of your repository on the runner.
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: mstachniuk/ci-skip@v1
      - name: Check if expression CI_SKIP and Test with Gradle
        if: ${{ env.CI_SKIP == 'false' }}
        run: ./gradlew test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: my-artifact
          path: build/reports

  Gradle_Check:
    needs: [ Gradle_Test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: mstachniuk/ci-skip@v1
      - name: Check if expression CI_SKIP and Check with Gradle
        if: ${{ env.CI_SKIP == 'false' }}
        run: ./gradlew check
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: my-artifact-2
          path: |
            build/reports
            !build/reports/tests
